// main.js - PHASE 2 FINAL (Corrected Points + Gold Rain Trigger)
// Full Pet Trigger Logic, Expanded NFTs, Input Scan (post-connect), Backend Call

// --- Imports ---
import { EthereumProvider } from '@walletconnect/ethereum-provider';
import { ethers } from 'ethers';
import html2canvas from 'html2canvas';

// --- Configuration Constants ---
const APECHAIN_RPC_URL = "https://apechain.rpc.ankr.com/";
const ALCHEMY_APECHAIN_RPC_URL = "https://ape-mainnet.g.alchemy.com/v2/vsd8ZH4Ouc0w_2YRow5MQ93Z3dIMAayQ"; // Your Key
const APECHAIN_CHAIN_ID = 33139;
const APECHAIN_NETWORK_INFO = { chainId: `0x${APECHAIN_CHAIN_ID.toString(16)}`, chainName: 'ApeChain', rpcUrls: [ALCHEMY_APECHAIN_RPC_URL], nativeCurrency: { name: 'APE', symbol: 'APE', decimals: 18 }, blockExplorerUrls: ['https://apescan.io'] };
const PROJECT_ID = 'f653591549f67bc5dc45ead5e636a12e';
const metadata = { name: 'DegenCheck App', description: 'ApeChain Wallet Scanner & Pet Affinity', url: window.location.origin, icons: [`${window.location.origin}/favicon.png`] };
const WALLET_CHECK_API_URL = 'https://lus6llhkrb.execute-api.eu-north-1.amazonaws.com/prod/wallet-check/';

// --- App Constants ---
const CULT_TOKEN_ADDRESS = "0xc7689ac46BC7a2c2819F0d9F280DC09C43295aBA";
const BAYC_SHADOW_ADDRESS = "0xBC4CA0EdA7647A8aB7C2061c2E118A18a936f13D";
const MAYC_SHADOW_ADDRESS = "0x60E4d786628Fea6478F785A6d7e704777c86a7c6";
const ZARDS_ADDRESS = "0x91417BD88AF5071CCea8d3BF3Af410660e356B06";
const HOPS_ADDRESS = "0xbe0c4F7aEF79e41463bcd4e20c66FdA4e35A5a19";
const GOBS_ADDRESS = "0xBEbaa24108d6a03C7331464270b95278bBBE6Ff7";
const MINO_ADDRESS = "0x8Af17673985E4032C6Ced41D35e9f5a3E694eD7F";
const NEKITO_ADDRESS = "0x23ABf38a6d3aD137C0B219b51243Cf326ed66039";
const DRNS_ADDRESS = "0x896BE40d15d1dbFA4F4Ff25A110F3CE770e07897";
const OOGIES_ADDRESS = "0x214cAE51c3BAE88515aAEfd8e1867E64502B0342";
const FROSTBYTE_ADDRESS = "0x5eDB0b26939764933c1ecFd99AB9379dfb62F4aD";
const RILLAZ_ADDRESS = "0xa128ECdb362786512aF9E8b16fC3bb5F96fF78e8";
const MUNKEE_ADDRESS = "0x13a9C4Ba78813ffCf8fc667DAEC043Af4f353C55";
const TG_ADDRESS = "0xd33edeC311f8769c71f132A77F0c0796c22AF1c5";
const GS_ADDRESS = "0xb3443B6Bd585ba4118CaE2beDb61c7EC4a8281Df";
const YUREI_ADDRESS = "0x0BDEF3d84b72031DD38FED41D3202becB2E8aef3";

// --- Pet Strategy/Display Data ---
const PET_DATA = {
  "Invo":     { name: "Invo",     strategyName: "Supertrend", description: "Long-term Trend Following", params: "Risk: Med, Freq: Low", supply: 105 },
  "Ape (Cult)":{ name: "Ape (Cult)", strategyName: "Stochastic Oscillator", description: "Trades Overbought/Oversold Swings", params: "Risk: Med, Freq: High", supply: 2500 },
  "Visor":    { name: "Visor",    strategyName: "Chaikin Money Flow", description: "Volume-Based Pressure Strategy", params: "Risk: Low-Med, Freq: Med", supply: 153 },
  "Ape (Red)": { name: "Ape (Red)",  strategyName: "Stochastic Oscillator", description: "Trades Overbought/Oversold Swings", params: "Risk: Med, Freq: High", supply: 2860 },
  "Ape (Blue)":{ name: "Ape (Blue)", strategyName: "Stochastic Oscillator", description: "Trades Overbought/Oversold Swings", params: "Risk: Med, Freq: High", supply: 2860 },
  "MrMonkee":   { name: "MrMonkee",   strategyName: "Stochastic Oscillator", description: "Trades Overbought/Oversold Swings", params: "Risk: Med, Freq: High", supply: 2500 },
  "Snake":      { name: "Snake",      strategyName: "CCI Strategy", description: "Trades Cyclical Extremes", params: "Risk: Med, Freq: Med", supply: 2750 },
  "Panther":    { name: "Panther",    strategyName: "CCI Strategy", description: "Trades Cyclical Extremes", params: "Risk: Med, Freq: Med", supply: 11000 },
  "Goblin":     { name: "Goblin",     strategyName: "ROC Threshold", description: "Momentum Burst Trading", params: "Risk: High, Freq: High", supply: 390 },
  "Cat":        { name: "Cat",        strategyName: "EMA Cross", description: "Short-term Trend Following", params: "Risk: Med, Freq: Med", supply: 480 },
  "Frog":       { name: "Frog",       strategyName: "Donchian Channel Breakout", description: "Volatility Breakout Trading", params: "Risk: Med-High, Freq: Low-Med", supply: 441 },
  "Seal":       { name: "Seal",       strategyName: "Bollinger Bands Mean Reversion", description: "Trades Reversals from Bands", params: "Risk: Low, Freq: Med-High", supply: 336 },
  "Squirrel":   { name: "Squirrel",   strategyName: "CCI Strategy", description: "Trades Cyclical Extremes", params: "Risk: Med, Freq: Med", supply: 153 },
  "Fox":        { name: "Fox",        strategyName: "TRIX", description: "Smoothed Momentum ROC", params: "Risk: Med, Freq: Low-Med", supply: 126 },
  "TokenGators":{ name: "TokenGators", strategyName: "Alpha Predator", description: "High-volatility focus", params: "Risk: High", supply: 0 },
  "Gorilla":    { name: "Gorilla",    strategyName: "MACD Trend", description: "Momentum Trend Following", params: "Risk: Med, Freq: Med-High", supply: 105 },
  "Raven":      { name: "Raven",      strategyName: "CCI Strategy", description: "Trades Cyclical Extremes", params: "Risk: Med, Freq: Med", supply: 2750 },
  "Blob":       { name: "Blob",       strategyName: "RSI Mean Reversion", description: "Trades Reversals from Extremes", params: "Risk: Low-Med, Freq: Med", supply: 3840 },
  "Crab":       { name: "Crab",       strategyName: "Range Navigator", description: "Default - No trigger conditions met.", params: "Risk: Low", supply: 1920 },
};

// --- NFT Configuration for Checks ---
// Points: Primary=+10, Secondary=+5 (Blobs/Globs=+10, Shadows=+25)
const ALL_NFTS_TO_CHECK = {
  // --- Primary Pet Trigger NFTs ---
  'MrMonkee':     { address: MUNKEE_ADDRESS, points: 10, isPrimary: true, triggersPet: "MrMonkee" },
  'Zards':        { address: ZARDS_ADDRESS, points: 10, isPrimary: true, triggersPet: "Snake" },
  'Hopstars':     { address: HOPS_ADDRESS, points: 10, isPrimary: true, triggersPet: "Panther" },
  'Gobs':         { address: GOBS_ADDRESS, points: 10, isPrimary: true, triggersPet: "Goblin" },
  'Minotaurs':    { address: MINO_ADDRESS, points: 10, isPrimary: true, triggersPet: "Goblin" },
  'Nekito':       { address: NEKITO_ADDRESS, points: 10, isPrimary: true, triggersPet: "Cat" },
  'DRNS':         { address: DRNS_ADDRESS, points: 10, isPrimary: true, triggersPet: "Frog" },
  'Oogies':       { address: OOGIES_ADDRESS, points: 10, isPrimary: true, triggersPet: "Seal" },
  'Frostbyte':    { address: FROSTBYTE_ADDRESS, points: 10, isPrimary: true, triggersPet: "Squirrel" },
  'Rillaz':       { address: RILLAZ_ADDRESS, points: 10, isPrimary: true, triggersPet: "Fox" },
  'TokenGators':  { address: TG_ADDRESS, points: 10, isPrimary: true, triggersPet: "TokenGators" },
  'GS on Ape':    { address: GS_ADDRESS, points: 10, isPrimary: true, triggersPet: "Gorilla" },
  'Yurei':        { address: YUREI_ADDRESS, points: 10, isPrimary: true, triggersPet: "Raven" },
  'MAYC Shadow':  { address: MAYC_SHADOW_ADDRESS, points: 0, isPrimary: true, triggersPet: "Blob" }, // Trigger only
  // --- NFTs Checked ONLY for Conditions/Bonus Points ---
  'BAYC Shadow':  { address: BAYC_SHADOW_ADDRESS, points: 0, isPrimary: false }, // Check for condition, points below
  // --- Bonus Point NFTs (isPrimary: false) ---
  "Blobs":      { address: "0x2c37897ad565F70163Ec979282CA3ac767094843", points: 10, isPrimary: false },
  "Globs":      { address: "0x73fA3797ca15d8758c3c45cdAFA63e7359964EC6", points: 10, isPrimary: false },
  "BAYC Shadow Bonus":{ address: BAYC_SHADOW_ADDRESS, points: 25, isPrimary: false }, // <<< UPDATED POINTS
  "MAYC Shadow Bonus":{ address: MAYC_SHADOW_ADDRESS, points: 25, isPrimary: false }, // <<< UPDATED POINTS
  "Ape Gang":   { address: "0xF36f4faDEF899E839461EccB8D0Ce3d49Cff5A90", points: 5, isPrimary: false },
  "Qoonicorns": { address: "0x6f8F60D8f390A149F8C111AF944B3989521d0184", points: 5, isPrimary: false },
  "Chaos Cats": { address: "0x027f7366f15f375a8EDDf9Ca768CBdC050DA8CDc", points: 5, isPrimary: false },
  "Skid City":  { address: "0xC78D0918D32146ab56146e18047021DA58a4f64b", points: 5, isPrimary: false },
  "Pasta Apes": { address: "0x682dD9B9e7b90707b854c46E1EF2637fEeaF090a", points: 5, isPrimary: false },
  "Wyatt wide world": { address: "0xf0fFa6a311eb8b9e11a1453AD08ED195b8e81601", points: 5, isPrimary: false },
  "Notapunkscult":{ address: "0xFA1c20E0d4277b1E0b289DfFadb5Bd92Fb8486aA", points: 5, isPrimary: false },
  "STK":          { address: "0xFa24048955CF7699A50EC1d2abcB0Cba89c08c38", points: 5, isPrimary: false },
  "Ape Pass Concierge": { address: "0x6D8F985bf0DC743dc1d81aEFf14A901cCE357ABC", points: 5, isPrimary: false },
  "Drifters":     { address: "0x9C732654399dBA1262Ffa8b2342b7FEFC8ee5EdB", points: 5, isPrimary: false },
  "Bags":         { address: "0xCF6d469911FfaBcb4911400E32e09c1BFc08FEBD", points: 5, isPrimary: false },
  "Sh/apes":      { address: "0x6986748Eb2e4b038c06cA6C916B72F02dE906B80", points: 5, isPrimary: false },
  "BrotherHOOD":  { address: "0x9F5C6d39c55131FE7752cBd88d53c67F9aFD3112", points: 5, isPrimary: false },
  "AlphaBanannas":{ address: "0xdFC7CD021514C55eEdC821E484217ee018E39028", points: 5, isPrimary: false },
  "Bored on chain":{ address: "0x80EAB3eD8f3c664827ac46dff9dd1758Ee402622", points: 5, isPrimary: false },
  "Chumpz":       { address: "0xa9a1d086623475595A02991664742E4A1cbAFcb8", points: 5, isPrimary: false },
  "Forever undead":{ address: "0x0178A9d0b0CBa1B2Ede3AFDb6dd021dB24fF4240", points: 5, isPrimary: false },
  "Banano":       { address: "0xD17384D1de685846C2dEc95dd17B52BabF821c68", points: 5, isPrimary: false },
  "Dragons":      { address: "0x942f916C60De629C0758542d4b08Fc1356309DFB", points: 5, isPrimary: false },
  "Dengs":        { address: "0x2CF92fe634909A9cF5e41291f54e5784d234cF8d", points: 5, isPrimary: false },
  "TrenchersOnApe":{ address: "0x1B094A5B06ce05FE443E7cF0B5fDcD6673eb735D", points: 5, isPrimary: false },
};

// ABIs
const nftAbi = ["function balanceOf(address owner) view returns (uint256)"];
const erc20Abi = ["function balanceOf(address owner) view returns (uint256)", "function decimals() view returns (uint8)"];

// --- DOM References ---
const connectBtn = document.getElementById('connectBtn'); const disconnectBtn = document.getElementById('disconnectBtn'); const walletInput = document.getElementById('walletInput'); const checkAddressBtn = document.getElementById('checkAddressBtn'); const scannedWalletInfo = document.getElementById('scannedWalletInfo'); const walletOutput = document.getElementById('walletOutput'); const resultArea = document.getElementById('resultArea'); const petSection = document.getElementById('petSection'); const petImage = document.getElementById('petImage'); const petText = document.getElementById('petText'); const scoreList = document.getElementById('scoreList'); const mintPass = document.getElementById('mintPass'); const bonusButtons = document.getElementById('bonusButtons'); const shareScoreBtn = document.getElementById('shareScoreBtn'); const goldRainCanvas = document.getElementById('goldRainCanvas');
console.log("DEBUG: Initial DOM Elements:", { connectBtn, disconnectBtn, walletInput, checkAddressBtn, shareScoreBtn });

// --- Application State ---
let wcProvider = null; let ethersProvider = null; let activeRawProvider = null; let signer = null;
let userAddress = null; let scannedAddress = null; let isCheckingConnectedWallet = false;
let totalScore = 0; let determinedPet = null; let scoreDetails = []; let cultFound = false;
let rainInterval = null; window.goldRainDrops = [];

// --- Helper Function Definitions ---
function shortenAddress(addr) { return addr ? `${addr.slice(0, 6)}...${addr.slice(-4)}` : ''; }
async function fetchFirstTransactionTimestamp(addressToCheck) { const apiUrl = `${WALLET_CHECK_API_URL}${addressToCheck}`; console.log("Calling backend:", apiUrl); let responseText; try { const response = await fetch(apiUrl); console.log(`DEBUG FETCH: Status: ${response.status}`); responseText = await response.text(); console.log("DEBUG FETCH: Raw Text:", responseText); if (!response.ok) { throw new Error(`Backend HTTP Error: ${response.status}`); } const bodyData = JSON.parse(responseText); console.log("DEBUG FETCH: Parsed Data:", bodyData); if (bodyData?.first_tx_timestamp) { const timestamp = parseInt(bodyData.first_tx_timestamp, 10); if (!isNaN(timestamp) && timestamp > 0) { return { timestamp: timestamp, message: null, error: null }; } else { console.warn("Invalid timestamp:", bodyData.first_tx_timestamp); return { timestamp: null, message: "Invalid format", error: null }; } } else if (bodyData?.message === "No transactions found") { return { timestamp: null, message: "No tx history", error: null }; } else if (bodyData?.error) { console.error("Backend error:", bodyData.error); return { timestamp: null, message: null, error: bodyData.error }; } else { console.warn("Unexpected format:", bodyData); throw new Error("Unexpected format"); } } catch (err) { console.error("fetchTimestamp Error:", err); if (err instanceof SyntaxError && typeof responseText !== 'undefined') { console.error("JSON Parse Fail Text:", responseText); return { error: "Non-JSON response" }; } return { error: err.message }; } }
function delay(ms) { return new Promise(resolve => setTimeout(resolve, ms)); }
async function displayGoblinSpam() { typeLine("GOB! GOB! GOB! GOB!", false); await delay(100); for (let i = 0; i < 5; i++) { typeLine("GOB! GOB! GOB! GOB! GOB! GOB!", false); await delay(80); } await delay(300); }

// --- Initialization ---
async function initializeWCProvider() { if (!PROJECT_ID) { console.error("FATAL: WC PROJECT_ID missing!"); return; } try { console.log("Init WC Provider..."); wcProvider = await EthereumProvider.init({ projectId: PROJECT_ID, chains: [APECHAIN_CHAIN_ID], showQrModal: false, rpcMap: { [APECHAIN_CHAIN_ID]: ALCHEMY_APECHAIN_RPC_URL }, metadata: metadata }); console.log("WC Provider initialized."); wcProvider.on('connect', async (p) => { console.log("WC Connect:", p); activeRawProvider = wcProvider; ethersProvider = new ethers.providers.Web3Provider(wcProvider, 'any'); await handleConnectionSuccess(); }); wcProvider.on('disconnect', handleProviderDisconnect); console.log("WC Listeners attached."); } catch (e) { console.error("Init WC Error:", e); wcProvider = null; } }

// --- State and UI Reset Functions ---
function resetState(clearOutput = true) { console.log("Resetting state."); activeRawProvider?.removeAllListeners?.(); ethersProvider = null; activeRawProvider = null; signer = null; userAddress = null; scannedAddress = null; isCheckingConnectedWallet = false; totalScore = 0; determinedPet = null; scoreDetails = []; cultFound = false; if (rainInterval) clearInterval(rainInterval); rainInterval = null; if (goldRainCanvas) goldRainCanvas.classList.add('hidden'); window.goldRainDrops = []; document.body.classList.remove('cult-3d-handshake'); if(clearOutput && walletOutput) walletOutput.innerHTML = ""; if(scannedWalletInfo) scannedWalletInfo.textContent = ""; }
function resetUI(clearOutput = true) { console.log("Resetting UI."); if(clearOutput && walletOutput) walletOutput.innerHTML = ""; if(scoreList) scoreList.innerHTML = ""; if(mintPass) mintPass.innerHTML = ""; if(scannedWalletInfo) scannedWalletInfo.textContent = ""; scannedWalletInfo.classList.add('hidden'); resultArea.classList.add('hidden'); petSection.classList.add('hidden'); bonusButtons.classList.add('hidden'); if (disconnectBtn) disconnectBtn.classList.add('hidden'); if (connectBtn) { connectBtn.classList.remove('hidden'); connectBtn.disabled = false; } if (checkAddressBtn) checkAddressBtn.disabled = false; if (walletInput) walletInput.disabled = false; }
function resetEverything(clearOutput = true) { resetState(clearOutput); resetUI(clearOutput); }

// --- Wallet Connection Logic ---
async function onConnectClick() { console.log("Connect clicked."); resetEverything(); walletOutput.innerHTML = "<p>Connecting...</p>"; if (typeof window.ethereum !== 'undefined') { console.log("Injected provider detected."); typeLine("Connecting via browser wallet..."); await connectInjected(window.ethereum); } else if (wcProvider) { console.log("Using WC fallback."); typeLine("Opening WalletConnect..."); await connectWalletConnect(); } else { console.error("No provider."); typeLine("❌ No wallet found.", true); resetEverything(); } }
async function connectInjected(injectedProvider) { try { typeLine("Requesting accounts..."); const accounts = await injectedProvider.request({ method: 'eth_requestAccounts' }); if (!accounts || accounts.length === 0) throw new Error("No accounts."); console.log("Injected accounts:", accounts); activeRawProvider = injectedProvider; ethersProvider = new ethers.providers.Web3Provider(activeRawProvider, 'any'); await handleConnectionSuccess(); } catch (error) { console.error("Injected connect error:", error); if (error.code === 4001) typeLine("❌ Request rejected.", true); else typeLine(`❌ Error: ${error.message}`, true); resetEverything(); } }
async function connectWalletConnect() { if (!wcProvider || wcProvider.connected) { console.warn("WC connect req invalid."); return; } walletOutput.innerHTML = "<p>Scan QR code...</p>"; try { await wcProvider.connect(); console.log("WC connect called."); } catch (error) { console.error("WC connect error:", error); if (error.message?.toLowerCase().includes('user closed modal')) typeLine("❌ Connection cancelled.", true); else typeLine(`❌ WC Error: ${error.message || 'Unknown'}.`, true); resetEverything(); } }
async function onScanAddressClick() { console.log("Scan Address button clicked."); if (!walletInput) { console.error("Input element missing."); return; } const addressFromInput = walletInput.value.trim(); if (!ethers.utils.isAddress(addressFromInput)) { alert("Invalid address format."); return; } resetUI(true); resultArea.classList.add('hidden'); if (scannedWalletInfo) { scannedWalletInfo.classList.remove('hidden'); scannedWalletInfo.textContent = `Scanning address: ${shortenAddress(addressFromInput)}...`; } else { typeLine(`Scanning address: ${shortenAddress(addressFromInput)}...`); } scannedAddress = addressFromInput; isCheckingConnectedWallet = false; let providerForScan = null; if (ethersProvider && userAddress) { try { const network = await ethersProvider.getNetwork(); if (network.chainId === APECHAIN_CHAIN_ID) { console.log("Using existing connected provider."); providerForScan = ethersProvider; } else { console.log("Connected provider on wrong network."); typeLine("⚠️ Wallet on wrong network. Switch to ApeChain.", true); } } catch (e) { console.warn("Err checking connected provider network:", e); } } if (!providerForScan) { console.log("Attempting read-only provider..."); try { const readOnlyProvider = new ethers.providers.JsonRpcProvider(ALCHEMY_APECHAIN_RPC_URL); await readOnlyProvider.getNetwork(); console.log("Read-only provider connected."); providerForScan = readOnlyProvider; } catch (providerError) { console.error("Failed read-only provider:", providerError); typeLine(`❌ Network connection failed. Connect wallet first.`, true); if(scannedWalletInfo) scannedWalletInfo.textContent = `Error connecting.`; if (checkAddressBtn) checkAddressBtn.disabled = false; if (walletInput) walletInput.disabled = false; return; } } if (providerForScan) { await runDegenCheck(providerForScan, scannedAddress); } else { console.error("Could not get provider for scan."); typeLine("❌ Scan failed: No network connection.", true); if (checkAddressBtn) checkAddressBtn.disabled = false; if (walletInput) walletInput.disabled = false; } }

// --- Post-Connection & Event Handlers ---
async function handleConnectionSuccess() { if (!ethersProvider || !activeRawProvider) { console.error("Conn Success missing provider."); return; } console.log("Handling conn success..."); try { signer = ethersProvider.getSigner(); userAddress = await signer.getAddress(); if (!userAddress) throw new Error("No address."); console.log("Connected as:", userAddress); connectBtn.classList.add('hidden'); disconnectBtn.classList.remove('hidden'); walletOutput.innerHTML = ''; typeLine(`[Wallet Connected: ${shortenAddress(userAddress)}]`); attachProviderListeners(activeRawProvider); scannedAddress = userAddress; isCheckingConnectedWallet = true; console.log("Checking network for connected..."); await checkAndSwitchNetwork(); console.log("Finished handleConnectionSuccess."); } catch (error) { console.error("Final connection error:", error); typeLine(`❌ Setup Error: ${error.message}`, true); await handleProviderDisconnect(); } }
async function checkAndSwitchNetwork() { if (!ethersProvider || !userAddress) { console.error("Cannot check network."); return; } console.log("Entering checkAndSwitchNetwork..."); try { const network = await ethersProvider.getNetwork(); console.log("Network:", network); if (network.chainId !== APECHAIN_CHAIN_ID) { typeLine(`⚠️ Wrong network (ID: ${network.chainId}). Requesting switch...`, true); await attemptSwitchNetwork(); const newNetwork = await ethersProvider.getNetwork(); if (newNetwork.chainId !== APECHAIN_CHAIN_ID) { typeLine(`❌ Switch failed. Scan aborted.`, true); resetUI(false); walletOutput.innerHTML = `<p>[Wallet Connected: ${shortenAddress(userAddress)}]</p><p style="color:red;">⚠️ Switch to ApeChain (ID ${APECHAIN_CHAIN_ID}).</p>`; connectBtn.classList.add('hidden'); disconnectBtn.classList.remove('hidden'); return; } else { typeLine(`[Network Switched]`); console.log("Network OK after switch, running scan..."); await runDegenCheck(ethersProvider, userAddress); } } else { typeLine(`[Network OK: ApeChain]`); console.log("Network OK, running scan..."); await runDegenCheck(ethersProvider, userAddress); } } catch (error) { console.error("Network check/switch error:", error); typeLine(`❌ Network Error: ${error.message}`, true); await handleProviderDisconnect(); } }
async function handleProviderDisconnect() { console.log("Handling disconnect."); activeRawProvider?.removeAllListeners?.(); if (activeRawProvider === wcProvider && wcProvider?.connected) { try { await wcProvider.disconnect(); } catch (e) { console.warn("WC disconnect error:", e); } } resetEverything(); typeLine("[Wallet Disconnected]"); }
function attachProviderListeners(provider) { if (!provider?.on) { console.warn("Cannot attach listeners."); return; } console.log("Attaching listeners..."); provider.removeAllListeners?.(); provider.on('accountsChanged', handleAccountsChanged); provider.on('chainChanged', handleChainChanged); provider.on('disconnect', handleProviderDisconnect); console.log("Listeners attached."); }
async function handleAccountsChanged(accounts) { console.log("Accounts Changed:", accounts); if (!activeRawProvider) return; if (!accounts || accounts.length === 0) { handleProviderDisconnect(); } else if (accounts[0].toLowerCase() !== userAddress?.toLowerCase()) { typeLine(`[Account Switched: ${shortenAddress(accounts[0])}]`); ethersProvider = new ethers.providers.Web3Provider(activeRawProvider, 'any'); signer = ethersProvider.getSigner(); userAddress = await signer.getAddress(); scannedAddress = userAddress; isCheckingConnectedWallet = true; console.log("Context updated. Re-checking..."); await checkAndSwitchNetwork(); } }
function handleChainChanged(chainId) { console.log("Chain Changed:", chainId); if (!userAddress) return; const numChainId = Number(chainId); if (isNaN(numChainId)) { console.error("Invalid chainId:", chainId); return; } if (numChainId !== APECHAIN_CHAIN_ID) { typeLine(`⚠️ Wrong network (ID: ${numChainId}). Switch back.`, true); resetUI(false); walletOutput.innerHTML = `<p>[Wallet Connected: ${shortenAddress(userAddress)}]</p><p style="color:red;">⚠️ Switch back to ApeChain.</p>`; connectBtn.classList.add('hidden'); disconnectBtn.classList.remove('hidden'); if (rainInterval) clearInterval(rainInterval); goldRainCanvas.classList.add('hidden'); } else { typeLine(`[Network OK: ApeChain]`); runDegenCheck(ethersProvider, userAddress); } }
async function attemptSwitchNetwork() { if (!ethersProvider?.send) { typeLine("❌ Cannot switch.", true); return Promise.reject("No provider send"); } typeLine(`[Requesting switch via wallet...]`); try { await ethersProvider.send('wallet_switchEthereumChain', [{ chainId: APECHAIN_NETWORK_INFO.chainId }]); console.log("Switch request sent."); return Promise.resolve(); } catch (switchError) { console.error("Switch Error:", switchError); if (switchError.code === 4902){ typeLine("[Requesting add network...]"); try { await ethersProvider.send('wallet_addEthereumChain', [APECHAIN_NETWORK_INFO]); console.log("Add request sent."); return Promise.resolve(); } catch (addError) { console.error("Add Error:", addError); typeLine("❌ Failed add.", true); return Promise.reject(addError); } } else { typeLine(`❌ Switch failed: ${switchError.message || '?'}.`, true); return Promise.reject(switchError); } } }

// --- Degen Check Core Logic ---
async function runDegenCheck(providerToCheck, addressToCheck) {
    console.log(`Entering runDegenCheck for address: ${addressToCheck}`);
    if (!addressToCheck || !providerToCheck) { typeLine("❌ Scan Error: Missing info.", true); return; }
    try { console.log("DEBUG: RPC Check..."); const bn = await providerToCheck.getBlockNumber(); console.log("DEBUG: RPC OK! Block:", bn); typeLine(`[RPC OK - Block: ${bn}]`); }
    catch (rpcError) { console.error("FATAL: RPC failed:", rpcError); typeLine(`❌ RPC Error: ${rpcError.message}. Scan aborted.`, true); resetEverything(false); return; }
    console.log(`Starting Scan for: ${addressToCheck}`); resultArea.classList.add('hidden'); petSection.classList.add('hidden'); scoreList.innerHTML = ""; mintPass.innerHTML = ""; bonusButtons.classList.add('hidden'); document.body.classList.remove('cult-3d-handshake'); if (rainInterval) clearInterval(rainInterval); goldRainCanvas.classList.add('hidden'); totalScore = 0; determinedPet = null; scoreDetails = []; cultFound = false;
    walletOutput.innerHTML = ""; if (isCheckingConnectedWallet && userAddress) { typeLine(`[Wallet Connected: ${shortenAddress(userAddress)}]`); } else if (scannedWalletInfo) { scannedWalletInfo.textContent = `Scanning: ${shortenAddress(addressToCheck)}...`; scannedWalletInfo.classList.remove('hidden'); }
    typeLine("[Initiating Scan...]"); if(connectBtn) connectBtn.disabled = true; if(disconnectBtn) disconnectBtn.disabled = true; if(checkAddressBtn) checkAddressBtn.disabled = true; if(walletInput) walletInput.disabled = true;
    try { await performWalletAnalysis(providerToCheck, addressToCheck); }
    catch (error) { console.error("Error during analysis:", error); typeLine("❌ Analysis error.", true); }
    finally { if(connectBtn) connectBtn.disabled = false; if(disconnectBtn) disconnectBtn.disabled = !isCheckingConnectedWallet; if(checkAddressBtn) checkAddressBtn.disabled = false; if(walletInput) walletInput.disabled = false; finalizeResults(addressToCheck); }
}

// ***** UPDATED: Comprehensive Analysis Function with Revised Points *****
async function performWalletAnalysis(provider, address) {
    typeLine("[1/5 Fetching Wallet Age...]");
    const dataFetchPromises = {}; dataFetchPromises.walletAge = fetchFirstTransactionTimestamp(address); await delay(150);
    typeLine("[2/5 Fetching Balances...]"); const cultContract = new ethers.Contract(CULT_TOKEN_ADDRESS, erc20Abi, provider); dataFetchPromises.cultBalanceRaw = cultContract.balanceOf(address).catch(e => { console.warn("CULT balance fail:", e); return ethers.BigNumber.from(0); }); dataFetchPromises.cultDecimals = cultContract.decimals().catch(e => { console.warn("CULT decimals fail:", e); return 18; }); const nftBalancePromises = []; for (const name in ALL_NFTS_TO_CHECK) { const nftData = ALL_NFTS_TO_CHECK[name]; if (ethers.utils.isAddress(nftData.address)) { const nftContract = new ethers.Contract(nftData.address, nftAbi, provider); nftBalancePromises.push( nftContract.balanceOf(address).then(b => ({ name, balance: b, config: nftData })).catch(e => { console.warn(`NFT ${name} fail:`, e); return { name, balance: ethers.BigNumber.from(0), config: nftData }; }) ); } else { console.warn(`Skipping ${name}: Invalid address ${nftData.address}`); } } dataFetchPromises.nftBalances = Promise.allSettled(nftBalancePromises);
    const fetchedResults = await Promise.allSettled(Object.values(dataFetchPromises)); const fetchedData = {}; Object.keys(dataFetchPromises).forEach((key, i) => { fetchedData[key] = (fetchedResults[i].status === 'fulfilled') ? fetchedResults[i].value : null; }); console.log("DEBUG: Fetched Data:", fetchedData); await delay(150);
    typeLine("[3/5 Processing Data...]"); const ageData = fetchedData.walletAge; if (ageData?.timestamp) { const date = new Date(ageData.timestamp * 1000); typeLine(`[Wallet Age: ${date.toISOString().split('T')[0]}]`); const cutoff = new Date("2024-12-31T23:59:59Z"); if (date < cutoff) { totalScore += 10; scoreDetails.push({ text: "Early Wallet: +10 pts", highlight: false }); typeLine("[Early Bonus Added!]"); } else { typeLine("[Wallet started post-cutoff]"); } } else if (ageData?.message) { typeLine(`[Wallet Age: ${ageData.message}]`); } else if (ageData?.error) { typeLine(`[Age Error: ${ageData.error}]`, true); } else { typeLine("[Age: Unavailable]"); }
    let cultBalance = 0; if (fetchedData.cultBalanceRaw) { const decimals = fetchedData.cultDecimals || 18; cultBalance = parseFloat(ethers.utils.formatUnits(fetchedData.cultBalanceRaw, decimals)); typeLine(`[$CULT: ${cultBalance.toFixed(2)}]`); if (cultBalance > 0) { cultFound = true; document.body.classList.add('cult-3d-handshake'); const pts = Math.min(Math.floor(cultBalance / 150000) * 1, 50); if(pts > 0){ totalScore += pts; scoreDetails.push({text:`$CULT: +${pts} pts`, highlight:false}); typeLine("[CULT Points Added!]"); } } else { cultFound = false; document.body.classList.remove('cult-3d-handshake'); } } else { typeLine("[⚠️ CULT Check Failed]"); } await delay(100);
    const nftBalances = {}; if (fetchedData.nftBalances) { fetchedData.nftBalances.forEach(r => { if (r.status === 'fulfilled' && r.value) { const { name, balance, config } = r.value; if(config && ethers.utils.isAddress(config.address)) nftBalances[config.address.toLowerCase()] = { name, balance, config }; } }); } console.log("DEBUG: Processed NFT Balances:", nftBalances);
    const getBalance = (addr) => nftBalances[addr?.toLowerCase()]?.balance || ethers.BigNumber.from(0); const holdsNft = (addr) => getBalance(addr).gt(0);
    if (holdsNft(BAYC_SHADOW_ADDRESS) || holdsNft(MAYC_SHADOW_ADDRESS)) { console.log("DEBUG: Yuga Asset Detected! Heist.exe..."); await delay(500); typeLine("!! ALERT !! Yuga Asset Detected!", true); await delay(500); typeLine("Initiating Heist.exe...", true); await delay(800); typeLine("Bypassing firewall...", true); await delay(500); typeLine("Heist protocols active.", true); await delay(500); typeLine("Delivering Pizza...", true); await delay(350); typeLine("SHADOW DETECTED. ABORT HEIST!", true); await delay(500); typeLine("No heist for dev.", true); await delay(300); typeLine("WoMp wOmP.", true); await delay(400); }
    typeLine("[4/5 Determining Pet...]"); determinedPet = null; const baycCount = getBalance(BAYC_SHADOW_ADDRESS).toNumber(); const maycCount = getBalance(MAYC_SHADOW_ADDRESS).toNumber(); const totalShadowsCount = baycCount + maycCount; console.log(`DEBUG Trigger Data: Cult=${cultBalance.toFixed(0)}, Shadows=${totalShadowsCount}`);
    if (!determinedPet && cultBalance >= 2000000 && totalShadowsCount >= 1) determinedPet = "Invo"; if (!determinedPet && cultBalance >= 500000 && totalShadowsCount >= 1) determinedPet = "Ape (Cult)"; if (!determinedPet && totalShadowsCount >= 6) determinedPet = "Ape (Red)"; if (!determinedPet && totalShadowsCount >= 1) determinedPet = "Ape (Blue)"; if (!determinedPet && cultBalance >= 500000) determinedPet = "Visor"; if (!determinedPet && holdsNft(MUNKEE_ADDRESS)) determinedPet = "MrMonkee"; if (!determinedPet && holdsNft(ZARDS_ADDRESS)) determinedPet = "Snake"; if (!determinedPet && holdsNft(HOPS_ADDRESS)) determinedPet = "Panther"; if (!determinedPet && (holdsNft(GOBS_ADDRESS) || holdsNft(MINO_ADDRESS))) determinedPet = "Goblin"; if (!determinedPet && holdsNft(NEKITO_ADDRESS)) determinedPet = "Cat"; if (!determinedPet && holdsNft(DRNS_ADDRESS)) determinedPet = "Frog"; if (!determinedPet && holdsNft(OOGIES_ADDRESS)) determinedPet = "Seal"; if (!determinedPet && holdsNft(FROSTBYTE_ADDRESS)) determinedPet = "Squirrel"; if (!determinedPet && holdsNft(RILLAZ_ADDRESS)) determinedPet = "Fox"; if (!determinedPet && holdsNft(TG_ADDRESS)) determinedPet = "TokenGators"; if (!determinedPet && holdsNft(GS_ADDRESS)) determinedPet = "Gorilla"; if (!determinedPet && holdsNft(YUREI_ADDRESS)) determinedPet = "Raven"; if (!determinedPet && holdsNft(MAYC_SHADOW_ADDRESS)) determinedPet = "Blob";
    if (!determinedPet) { determinedPet = "Crab"; console.log("DEBUG: Defaulting to Crab."); } else { console.log(`DEBUG: Pet Determined: ${determinedPet}`); }
    if (determinedPet === "Goblin") { console.log("DEBUG: Goblin determined, running spam"); await displayGoblinSpam(); }
    typeLine(`[Determined Pet: ${determinedPet}]`); await delay(150);

    typeLine("[5/5 Calculating Points...]"); let primaryPointsAdded = 0; let secondaryPointsAdded = 0;
    // --- Logic WITHOUT points cap ---
    for(const name in ALL_NFTS_TO_CHECK) { const config = ALL_NFTS_TO_CHECK[name]; if (config && ethers.utils.isAddress(config.address)) { const balance = getBalance(config.address); if (balance.gt(0)) { const pointsToAdd = config.points || 0; if (pointsToAdd > 0) { let alreadyCountedForGoblin = false; if (config.triggersPet === "Goblin" && scoreDetails.some(item => item.text.startsWith("Goblin:"))) alreadyCountedForGoblin = true; if (!alreadyCountedForGoblin) { totalScore += pointsToAdd; scoreDetails.push({ text: `${name}: +${pointsToAdd} pts`, highlight: config.isPrimary || pointsToAdd >= 10 }); console.log(`DEBUG: Added ${pointsToAdd} pts for ${name}`); if (config.isPrimary) primaryPointsAdded += pointsToAdd; else secondaryPointsAdded += pointsToAdd; } else { console.log(`DEBUG: Skipping duplicate Goblin pts for ${name}`); } } } } }
    console.log(`DEBUG: Points Complete. Primary Total: ${primaryPointsAdded}, Secondary Total: ${secondaryPointsAdded}`); await delay(150);
}
// ***** END OF Analysis Function *****


// --- Final Results Display & Effects ---
function finalizeResults(addressChecked) { console.log(`Finalizing for ${addressChecked}. Score: ${totalScore}`); setTimeout(() => { typeLine("[Scan Complete]"); showFinalScore(addressChecked); }, 300); }
function showFinalScore(addressChecked) { console.log(`Displaying results for ${addressChecked}. Pet: ${determinedPet}`); resultArea.classList.remove("hidden"); const petKey = determinedPet || "Crab"; const petData = PET_DATA[petKey]; if (!petData) { console.error(`Data missing for pet: ${petKey}`); petText.innerHTML=`<strong>Error! Pet data missing.</strong>`; petImage.src=''; } else { const imgName = petKey.replace(/[\s()]/g, ''); petImage.src = `/PetPromos/${imgName}promo.png`; petImage.alt = `${petData.name} Pet Image`; petText.innerHTML = `<strong>Pet: ${petData.name}</strong><br>Strategy: ${petData.strategyName}<br><em>${petData.description || ''}</em><br><small>Params: ${petData.params || ''}</small>`; console.log(`DEBUG: Set pet img src: ${petImage.src}`); } petSection.classList.remove("hidden"); scoreList.innerHTML = ''; scoreDetails.sort((a, b) => (a.highlight === b.highlight)? a.text.localeCompare(b.text) : a.highlight ? -1 : 1 ); if(scoreDetails.length===0) { scoreList.innerHTML='<li>No specific scoring actions.</li>'; } else { scoreDetails.forEach(item => { const li = document.createElement('li'); li.innerHTML = item.text; if(item.highlight) li.classList.add('neon-highlight'); scoreList.appendChild(li); }); } const totalLi = document.createElement('li'); totalLi.innerHTML = `<strong>Total Score: ${totalScore} pts</strong>`; totalLi.style.cssText = 'margin-top:15px; border-top:1px solid #00f5ff; padding-top:10px;'; scoreList.appendChild(totalLi); if (!isCheckingConnectedWallet && scannedAddress) { scannedWalletInfo.textContent = `Showing results for: ${shortenAddress(scannedAddress)}`; scannedWalletInfo.classList.remove('hidden'); } else { scannedWalletInfo.classList.add('hidden'); } if (isCheckingConnectedWallet && userAddress && userAddress.toLowerCase() === addressChecked?.toLowerCase()) { console.log(`DEBUG: Checking eligibility. Score: ${totalScore}`); if (totalScore >= 50) { mintPass.innerHTML="✅ Degen Confirmed! Presale Access Granted."; mintPass.style.color="#00f5ff"; bonusButtons.classList.remove('hidden'); startGoldRain(); } else { mintPass.innerHTML=`Score ${totalScore} // Need 50+ pts for Presale Access.`; mintPass.style.color="orange"; bonusButtons.classList.add('hidden'); } } else { console.log("DEBUG: Hiding bonus buttons."); mintPass.innerHTML = `Scan complete for ${shortenAddress(addressChecked)}. Connect wallet to check eligibility.`; mintPass.style.color="grey"; bonusButtons.classList.add('hidden'); } }
function typeLine(text, isError = false) { console.log(`DEBUG: typeLine: "${text}"`); if (!walletOutput) return; const line = document.createElement('p'); line.style.cssText="margin:0; font-family:'Roboto Mono',monospace; font-size:0.9em; opacity:0; word-break:break-word;"; if(isError){ line.style.color="#ff4d4d"; line.textContent=`❌ ${text}`; line.style.opacity=1; } else { line.style.color="#00ff88"; line.textContent = ""; let i=0; const interval = setInterval(()=>{ if(!line.parentNode) { clearInterval(interval); return; } line.style.opacity=1; line.textContent=text.slice(0,i++)+"█"; if(i > text.length){ clearInterval(interval); if(line) line.textContent=text; } }, 20); } /* SLOWED TYPING */ walletOutput.insertBefore(line, walletOutput.firstChild); while(walletOutput.children.length > 25) { if (walletOutput.lastChild) walletOutput.removeChild(walletOutput.lastChild); else break; } }
function startGoldRain() { if(!goldRainCanvas) return; const ctx=goldRainCanvas.getContext('2d'); if(!ctx) return; console.log("Starting gold rain."); goldRainCanvas.classList.remove('hidden'); window.goldRainDrops=[]; resizeCanvas(); window.removeEventListener('resize', resizeCanvas); window.addEventListener('resize', resizeCanvas); if(rainInterval) clearInterval(rainInterval); for(let i=0; i<100; i++) window.goldRainDrops.push({x:Math.random()*goldRainCanvas.width, y:Math.random()*goldRainCanvas.height-goldRainCanvas.height, length:Math.random()*20+10, speed:Math.random()*5+2}); rainInterval = setInterval(drawRain, 33); setTimeout(() => { console.log("Stopping gold rain."); if (rainInterval) clearInterval(rainInterval); rainInterval = null; if (goldRainCanvas) goldRainCanvas.classList.add('hidden'); if(ctx) ctx.shadowBlur = 0; window.goldRainDrops = []; window.removeEventListener('resize', resizeCanvas); }, 10000); }
function resizeCanvas() { if(!goldRainCanvas) return; goldRainCanvas.width=window.innerWidth; goldRainCanvas.height=window.innerHeight; }
function drawRain() { if(!goldRainCanvas || !window.goldRainDrops) { if(rainInterval) clearInterval(rainInterval); return; } const ctx=goldRainCanvas.getContext('2d'); const drops=window.goldRainDrops; if(!ctx || !drops || drops.length===0) return; ctx.clearRect(0,0,goldRainCanvas.width, goldRainCanvas.height); ctx.fillStyle='#FFD700'; ctx.shadowColor='#FFFF00'; ctx.shadowBlur=10; for(let i=0; i<drops.length; i++){ let d=drops[i]; if(!d) continue; ctx.fillRect(d.x, d.y, 2, d.length); d.y+=d.speed; if(d.y>goldRainCanvas.height){ if(window.goldRainDrops[i]) window.goldRainDrops[i]={x:Math.random()*goldRainCanvas.width, y:-20, length:Math.random()*20+10, speed:Math.random()*5+2}; } } }

// --- Event Listener Attachments ---
console.log("DEBUG: Attaching final event listeners...");
connectBtn?.addEventListener('click', onConnectClick);
disconnectBtn?.addEventListener('click', handleProviderDisconnect);
checkAddressBtn?.addEventListener('click', onScanAddressClick);
shareScoreBtn?.addEventListener('click', () => { console.log("DEBUG: Share Score Clicked"); typeLine("[Generating image...]"); setTimeout(() => { const s=document.querySelector("#scoreBreakdown"), p=document.querySelector("#petSection"); if(!s||!p){ console.error("Screenshot elements missing"); typeLine("❌ Screenshot Error.", true); return; } const o = {scale:window.devicePixelRatio||2, backgroundColor:'#0f0f1a', useCORS:true, logging:false}; html2canvas(s, o).then(c1=>{ html2canvas(p,o).then(c2=>{ const cv=document.createElement('canvas'), pad=20*o.scale; cv.width=Math.max(c1.width,c2.width); cv.height=c1.height+c2.height+pad; const ct=cv.getContext('2d'); ct.fillStyle=o.backgroundColor; ct.fillRect(0,0,cv.width,cv.height); ct.drawImage(c1,0,0); ct.drawImage(c2,0,c1.height+pad); const l=document.createElement('a'); l.download=`DegenCheck_${scannedAddress?shortenAddress(scannedAddress):'Wallet'}_${Date.now()}.png`; l.href=cv.toDataURL("image/png"); l.click(); typeLine("[✅ Score image saved!]"); }).catch(e=>{console.error("Screenshot pet err:",e); typeLine("❌ Screenshot Error (pet).", true);}) }).catch(e=>{console.error("Screenshot score err:",e); typeLine("❌ Screenshot Error (score).", true);}) }, 200); });
console.log("DEBUG: Event listeners attached.");

// --- Initial Page Load Setup ---
document.addEventListener('DOMContentLoaded', () => { console.log("DEBUG: DOMContentLoaded fired."); const yearElement = document.getElementById('year'); if (yearElement) yearElement.textContent = new Date().getFullYear(); else console.warn("Year element missing"); initializeWCProvider(); resetEverything(); typeLine("System Online // Ready"); console.log("DEBUG: DOMContentLoaded handler finished."); });